### ISSUE TITLE
Cannot find ruby.h with --homebrew-ruby

### ISSUE THREAD

**Issue by alanthing** [sportngin/brew-gem#52]
```
$ brew-gem install aws_assume_role --homebrew-ruby
==> Fetching aws_assume_role from gem source
Downloaded aws_assume_role-1.1.0-universal-darwin
Warning: Cannot verify integrity of aws_assume_role-1.1.0.gem
A checksum was not provided for this resource
For your reference the SHA256 is: 3c9dce81790b292f2744123a84f887f0d8a93b14dc126d12e29a903875fdc254
==> /usr/local/bin/gem install /Users/alan/Library/Caches/Homebrew/aws_assume_role-1.1.0.gem --no-ri --no-rdoc --no-wrapper --no-user-install --install-dir /usr/local/Cellar/gem-aws_assume_role/1.1.0
Last 15 lines from /Users/alan/Library/Logs/Homebrew/gem-aws_assume_role/01.gem:
         ^~~~~~~~
1 error generated.
make: *** [Buffer.o] Error 1
make: *** [Call.o] Error 1
1 error generated.
1 error generated.
make: *** [Function.o] Error 1
make: *** [ClosurePool.o] Error 1
1 error generated.
make: *** [AbstractMemory.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/Cellar/gem-aws_assume_role/1.1.0/gems/ffi-1.9.18 for inspection.
Results logged to /usr/local/Cellar/gem-aws_assume_role/1.1.0/extensions/x86_64-darwin-17/2.5.0/ffi-1.9.18/gem_make.out

Do not report this issue to Homebrew/brew or Homebrew/core!
```

[Contents of 01.gem are in this gist](https://gist.github.com/alanthing/b6b464365d7c843cf008149a13715805#file-gistfile1-txt).

If I run the displayed gem command manually, it completes successfully. I tried a few other gems and have the same result. I'm not clear on why it's not found because it's accessible in the `/usr/local/include/` tree (via a subdirectory):

```
$ find -L /usr/local -name ruby.h
/usr/local/Cellar/ruby/2.5.0/include/ruby-2.5.0/ruby/ruby.h
/usr/local/Cellar/ruby/2.5.0/include/ruby-2.5.0/ruby.h
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/include/ruby-2.3.0/ruby/ruby.h
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/include/ruby-2.3.0/ruby.h
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/include/ruby-2.3.0/ruby/ruby.h
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/include/ruby-2.3.0/ruby.h
/usr/local/include/ruby-2.5.0/ruby/ruby.h
/usr/local/include/ruby-2.5.0/ruby.h
/usr/local/opt/ruby/include/ruby-2.5.0/ruby/ruby.h
/usr/local/opt/ruby/include/ruby-2.5.0/ruby.h
/usr/local/opt/ruby@2.5/include/ruby-2.5.0/ruby/ruby.h
/usr/local/opt/ruby@2.5/include/ruby-2.5.0/ruby.h
/usr/local/var/homebrew/linked/ruby/include/ruby-2.5.0/ruby/ruby.h
/usr/local/var/homebrew/linked/ruby/include/ruby-2.5.0/ruby.h
```

**Comment by nicksieger** [comment]
I've noticed this issue too but haven't tracked down the cause. I've been in `--debug` shells and still had no luck. Let me know if you figure anything out, would be happy to merge a PR that fixes this.

**Comment by nicksieger** [comment]
Figured out a fix for this issue. It's in #53, specifically commit fcdc522a46b73470e4e2be51c8451a38f687e542.

I found that Homebrew's shims do a bunch of option-passing through environment variables. Specifically, what was happening is that the Homebrew shim for `make` was setting an `O` option in the environment variable `HOMEBREW_CCCFG` which was picked up by the shim for `clang` which then ran some logic called `refurbish_args`. I didn't take the time to understand what that meant, but I found that this logic was breaking gem native extension compiles.

**Comment by alanthing** [comment]
Nice, thanks @nicksieger . What's the best way for me to test? I'm assuming some kind local/HEAD install of brew-gem on your branch; how would I do that?

**Comment by nicksieger** [comment]
Yeah, pull down the branch in the #53 and try running `./bin/brew-gem install ...`.

**Comment by alanthing** [comment]
Apologies for the late reply here. I've tried both the direct branch mentioned in #53 and the latest brew-gem (b/c I can see it was merged) and I'm seeing similar behavior I believe:

```
$ brew-gem install keyring
==> Fetching keyring from gem source
Fetching: keyring-0.4.1.gem (100%)
Downloaded keyring-0.4.1
Warning: Cannot verify integrity of keyring-0.4.1.gem
A checksum was not provided for this resource
For your reference the SHA256 is: f58c31f5437c689e15271d44d69b5f86985a137fc6e8519221bcd433a7a02c37
==> /usr/bin/gem install /Users/alan/Library/Caches/Homebrew/keyring-0.4.1.gem --no-ri --no-rdoc --no-wrapper --no-user-install --install-dir /usr/local/Cellar/gem-keyring/0.4.1 --bindir /usr/local/C
Last 15 lines from /Users/alan/Library/Logs/Homebrew/gem-keyring/01.gem:

    current directory: /usr/local/Cellar/gem-keyring/0.4.1/gems/keyring-0.4.1/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby mkrf_conf.rb
*osx: installing ruby-keychain

current directory: /usr/local/Cellar/gem-keyring/0.4.1/gems/keyring-0.4.1/ext
rake RUBYARCHDIR=/usr/local/Cellar/gem-keyring/0.4.1/extensions/universal-darwin-17/2.3.0/keyring-0.4.1 RUBYLIBDIR=/usr/local/Cellar/gem-keyring/0.4.1/extensions/universal-darwin-17/2.3.0/keyring-0.4.1
/Library/Ruby/Site/2.3.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.3.0/rubygems.rb:308:in `activate_bin_path'
	from /usr/bin/rake:23:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /usr/local/Cellar/gem-keyring/0.4.1/gems/keyring-0.4.1 for inspection.
Results logged to /usr/local/Cellar/gem-keyring/0.4.1/extensions/universal-darwin-17/2.3.0/keyring-0.4.1/gem_make.out

Do not report this issue to Homebrew/brew or Homebrew/core!
```

[The contents of 01.gem are here](https://gist.github.com/alanthing/bf8c0b1ddcbc6eced573d5c1a563a221#file-01-gem) (and, despite the message, there's actually nothing in `/usr/local/Cellar/gem-keyring/`).

The log spits out that it died trying to run `/usr/local/bin/gem install /Users/alan/Library/Caches/Homebrew/keyring-0.4.1.gem --no-ri --no-rdoc --no-wrapper --no-user-install --install-dir /usr/local/Cellar/gem-keyring/0.4.1 --bindir /usr/local/Cellar/gem-keyring/0.4.1/bin`, which actually works fine if I run that manually.

Thanks for reading -- what else can I do to troubleshoot? Does this have anything to do with being a native extension?

**Comment by nicksieger** [comment]
From your log I can see that it's trying to install gems with `/usr/bin/gem`, which is the (old) system ruby. Can you try again with homebrew ruby installed?
